package deps, docker updates

diff --git a/bkjs b/bkjs
--- a/bkjs
+++ b/bkjs
@@ -445,15 +445,27 @@ case "$BKJS_CMD" in
     cmd=install
     [ ! -z "$(get_flag -update)" ] && cmd=update
     npm=$(get_arg -npm)
-    [ ! -z "$(get_flag -global)" ] && npm="$npm -g"
-    fields=$(get_arg -fields dependencies,devDependencies)
-    skip=$(get_arg -skip $BKJS_MOD)
     path=$(get_arg -path .)
+    strict=$(get_flag -strict)
+    global=$(get_flag -global)
+    skip=$(get_arg -skip $BKJS_MOD)
+    fields=$(get_arg -fields dependencies,devDependencies)
     for p in $path; do
-        m=$($NODE_BIN -e "try{skip='$skip';p=require('$p/package.json');console.log('$fields'.split(',').map(f=>(Object.keys(p[f]||{}).filter(x=>(!x.match(skip))).map(x=>(x+(p[f][x][0]=='^'?'@'+p[f][x].substr(1).split('.')[0]:''))).join(' '))).join(' '))}catch(e){if('$BKJS_DEBUG')console.log(e)}")
+        m=$($NODE_BIN -e "try{skip='$skip';p=require('$p/package.json');console.log('$fields'.split(',').map(f=>(Object.keys(p[f]||{}).filter(x=>(!x.match(skip))).map(x=>(x+(!'$strict'&&p[f][x][0]=='^'?'@'+p[f][x].substr(1).split('.')[0]:''))).join(' '))).join(' '))}catch(e){if('$BKJS_DEBUG')console.error(e)}")
         [ "$m" != "" ] && modules="$modules $m"
     done
     [[ -z $modules ]] && exit 0
+    if [ ! -z $strict ]; then
+        npath=./node_modules
+        [ ! -z $global ] && npath=$NODE_PATH
+        mods=""
+        for m in $modules; do
+            m=$($NODE_BIN -e "try{p=require('$npath/$m/package.json');console.log(p.name+'@'+p.version)}catch(e){console.error(e)}")
+            [ ! -z $m ] && mods="$mods $m"
+        done
+        modules=$mods
+    fi
+    [ ! -z $global ] && npm="$npm -g"
     echo "$NPM_BIN $npm $cmd $modules"
     [ ! -z "$(get_flag -dry-run)" ] && exit 0
     $NPM_BIN $npm $cmd $modules
@@ -685,7 +697,7 @@ case "$BKJS_CMD" in
     echo "  watch - run the backend in watcher and master mode with all source files being monitored for changes, the server is restarts on any change automatically"
     echo "  run - run local backend with provided arguments"
     echo "  logwatcher - runs the log watcher and exists, for cases when no $BKJS service is running but the error log must be watched"
-    echo "  deps [-fields dependencies,devDependencies] [-path .] [-skip REGEXP] [-global] [-update] [-npm ARGS] - install npm packages from the dependencies list from the package.json"
+    echo "  deps [-fields dependencies,devDependencies] [-path .] [-skip REGEXP] [-global] [-update] [-strict] [-npm ARGS] - install npm packages from the dependencies list from the package.json"
     echo "  sync [-host HOST] [-path PATH] [-user USER] [-ssh-key pem] [-ssh OPTS] [-exclude PATTERN] [-bkcmd CMD] - push the backend code to the remote host using rsync, default path is ~/node_modules/$BKJS_MOD"
     echo "  ssh -host HOST -cmd CMD [-user USER] [-key PEM] [-ssh ARGS] - run a command over ssh on all specified hosts"
     echo "  install-node [-prefix PATH] [-force] [-clean] - install binary release of the node into $BKJS_PREFIX or specified path"
diff --git a/tools/bkjs-aws b/tools/bkjs-aws
--- a/tools/bkjs-aws
+++ b/tools/bkjs-aws
@@ -308,13 +308,16 @@ case "$BKJS_CMD" in
 
   ecr-push)
     tag=$(get_arg -tag)
-    [ "$tag" = "" ] && echo "-tag are required" && exit 1
+    [ "$tag" = "" ] && echo "-tag is required" && exit 1
     ecr="$($0 ec2-account).dkr.ecr.$($0 ec2-region).amazonaws.com"
     aws ecr get-login-password| docker login --username AWS --password-stdin $ecr
     [ "$?" != "0" ] && exit 1
     ecr="$ecr/$tag"
     version=$(get_arg -version)
     [ ! -z $version ] && ecr="$ecr:$version"
+    if [ ! -z $(get_flag -force) ]; then
+        aws ecr batch-delete-image --repository-name $tag --image-ids imageTag=${version:-latest}
+    fi
     docker tag $tag $ecr
     docker push $ecr
     ;;
@@ -344,10 +347,10 @@ case "$BKJS_CMD" in
         [ ! -z $overrides ] && overrides="$overrides,"
         overrides="$overrides\"memory\":$mem"
     fi
-    arch=$(get_arg -arch)
-    if [ ! -z $arch ]; then
+    arm=$(get_arg -arm)
+    if [ ! -z $arm ]; then
         [ ! -z $overrides ] && overrides="$overrides,"
-        overrides="$overrides\"runtimePlatform\":{\"cpuArchitecture\":\"$arch\"}"
+        overrides="$overrides\"runtimePlatform\":{\"cpuArchitecture\":\"ARM64\"}"
     fi
 
     tag=$(get_arg -tag)
@@ -368,6 +371,7 @@ case "$BKJS_CMD" in
         cmd="$cmd --capacity-provider-strategy capacityProvider=$(get_arg -provider FARGATE)"
     fi
 
+    [ ! -z "$BKJS_DEBUG" ] && echo $cmd
     [ ! -z $(get_flag -dry-run) ] && echo $cmd && exit
 
     $cmd
@@ -389,7 +393,8 @@ case "$BKJS_CMD" in
     echo "  create-launch-template-version [-name NAME] [-skip A B] [-image-name *] - create new launch template verson with the latest AMI, if no -name is given all existing templates will be updated"
     echo "  init-sendmail-ses - [-domain DOMAIN] -alert-host HOST -alert-user USER -alert-password PW - configure sendmail as relay to SES SMTP"
     echo "  init-cloudwatch-agent [-restart] - install AWS Cloudwatch agent to send backend logs to Cloudwatch Logs"
-    echo "  ecr-push -t TAG - tag and push a docker image to ECR"
+    echo "  ecr-push -tag NAME [-version V] [-force] - tag and push a docker image to ECR"
+    echo "  ecs-run -task NAME [-cluser default] [-type EC2|FARGATE] [-provider FARGATE_SPOT] [-gid ID] [-group NAME] [-sid ID] [-subnet NAME] [-cpu N] [-memory N] [-tag T] [-arm] [-exec] [-dry-tun] - run an ECS task in subnets with security groups, overrides cpu/mem, pass tag to bkjs process as instance tag"
     ;;
 
   *)
diff --git a/tools/bkjs-docker b/tools/bkjs-docker
--- a/tools/bkjs-docker
+++ b/tools/bkjs-docker
@@ -9,45 +9,45 @@ case "$BKJS_CMD" in
   docker-build)
     tag=$(get_arg -tag)
     version=$(get_arg -version)
-    path=$(get_arg -path $HOME)
-    root=$(get_arg -root $BKJS_HOME/docker)
+    path=$(get_arg -path .)
+    root=$(get_arg -root $HOME)
 
-    [ ! -f $root/$tag.Dockerfile ] && echo "$BKJS_CMD: no $tag.Dockerfile found in $root" && exit 1
+    [ ! -f $path/$tag.Dockerfile ] && echo "$BKJS_CMD: no $tag.Dockerfile found in $path" && exit 1
 
-    [ -f $root/$tag.path ] && path="$path$(cat $root/$tag.path)"
-    [ ! -d $path ] && echo "$BKJS_CMD: invalid $tag context path: $path" && exit 1
+    [ -f $path/$tag.path ] && path="$root$(cat $path/$tag.path)"
+    [ ! -d $root ] && echo "$BKJS_CMD: invalid $tag context path: $root" && exit 1
 
-    rm -f $path/.dockerignore
-    [ -f $root/$tag.dockerignore ] && cp $root/$tag.dockerignore $path/.dockerignore
+    rm -f $root/.dockerignore
+    [ -f $path/$tag.dockerignore ] && cp $path/$tag.dockerignore $root/.dockerignore
 
-    [ -f $root/$tag.build ] && cmd=$(cat $root/$tag.build)
+    [ -f $path/$tag.build ] && cmd=$(cat $path/$tag.build)
     [ ! -z $version ] && cmd="$cmd -t $tag:$version"
 
-    cmd="docker build -t $tag -f $root/$tag.Dockerfile $cmd $path"
+    cmd="docker build --progress=plain -t $tag -f $path/$tag.Dockerfile $cmd $root"
     [ ! -z "$BKJS_DEBUG" ] && echo $cmd
 
     $cmd
     rc=$?
 
-    rm -f $path/.dockerignore
+    rm -f $root/.dockerignore
     [ "$rc" != "0" ] && exit $rc
 
-    [ "$(get_flag -run)" != "" ] && $0 docker-run -tag $tag -root $root -force
+    [ "$(get_flag -run)" != "" ] && $0 docker-run -tag $tag -path $path -force
     ;;
 
   docker-run)
     tag=$(get_arg -tag)
-    root=$(get_arg -root $BKJS_HOME/docker)
+    path=$(get_arg -path .)
 
     [ -z $tag ] && echo "$BKJS_CMD: -tag must be provided" && exit 1
-    [ -f $root/$tag.run ] && cmd=$(cat $root/$tag.run)
+    [ -f $path/$tag.run ] && cmd=$(cat $path/$tag.run)
 
     if [ "$(get_flag -force)" != "" ]; then
        pids=$(docker ps -aq -f name=$tag)
        [ ! -z $pids ] && docker rm -f $pids
     fi
 
-    cmd="docker run -d --name $tag $cmd $tag $(get_all_args "-tag -root -force")"
+    cmd="docker run -d --name $tag $cmd $tag $(get_all_args "-tag -path -force")"
     [ ! -z "$BKJS_DEBUG" ] && echo $cmd
 
     $cmd
@@ -66,7 +66,7 @@ case "$BKJS_CMD" in
        echo "local1.* $BKJS_HOME/log/docker.log$bkjsfmt" >> /etc/rsyslog.d/$BKJS-docker.conf
        service rsyslog restart
 
-       echo '{ "log-driver": "syslog", "log-opts": { "tag": "{{.Name}}", "syslog-facility": "local1", "cache-disabled": "true", "mode": "non-blocking" } }' > /etc/docker/daemon.json
+       echo '{ "features": { "buildkit": true }, "log-driver": "syslog", "log-opts": { "tag": "{{.Name}}", "syslog-facility": "local1", "cache-disabled": "true", "mode": "non-blocking" } }' > /etc/docker/daemon.json
        service docker restart
     fi
     ;;
@@ -80,8 +80,8 @@ case "$BKJS_CMD" in
     echo "Docker commands:"
     echo ""
     echo "docker-init-rsyslog - store docker container logs in $BKJS_HOME/log/docker.log"
-    echo "docker-build -t TAG - build an image for the specified tag"
-    echo "docker-run -t TAG - run a container for the specified tag"
+    echo "docker-build -t TAG [-version V] [-path .] [-root H] - build an image for the specified tag"
+    echo "docker-run -t TAG [-path .] [-force] - run a container for the specified tag"
     echo "drestart NAME - restart a container, for use with bkrsync"
     ;;
 
