docker ecr

diff --git a/tools/bkjs-docker b/tools/bkjs-docker
--- a/tools/bkjs-docker
+++ b/tools/bkjs-docker
@@ -32,14 +32,6 @@ case "$BKJS_CMD" in
     rm -f $path/.dockerignore
     [ "$rc" != "0" ] && exit $rc
 
-    ecr=$(get_arg -ecr)
-    if [ "$ecr" != "" ]; then
-        region=$(get_arg -region uc-east-1)
-        aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $ecr
-        docker tag $tag $ecr:$tag
-        docker push $ecr:$tag
-    fi
-
     [ "$(get_flag -run)" != "" ] && $0 docker-run -tag $tag -root $root -force
     ;;
 
@@ -87,15 +79,28 @@ case "$BKJS_CMD" in
     fi
     ;;
 
+  docker-ecr)
+    tag=$(get_arg -tag)
+    [ "$tag" = "" ] && echo "-tag are required" && exit 1
+    ecr="$($0 ec2-account).dkr.ecr.$($0 ec2-region).amazonaws.com"
+    aws ecr get-login-password| docker login --username AWS --password-stdin $ecr
+    [ "$?" != "0" ] && exit 1
+    ecr="$ecr/$tag"
+    [ ! -z $version ] && ecr="$ecr:$version"
+    docker tag $tag $ecr
+    docker push $ecr
+    ;;
+
   help)
     echo ""
     echo "Docker commands:"
     echo ""
-    echo "docker-build|dbuild -t tag - build an image for the specified tag"
-    echo "docker-run|drun -t tag - run a container for the specified tag"
+    echo "docker-build|dbuild -t TAG - build an image for the specified tag"
+    echo "docker-run|drun -t TAG - run a container for the specified tag"
     echo "docker-init-rsyslog - setup rsyslog driver for docker containers"
     echo "docker-exec|dexec NAME .... - send a command to a running container"
     echo "docker-restart|drestart NAME - restart a container"
+    echo "docker-ecr -t TAG - tag and push an image to ECR"
     ;;
 
   *)
