es upgrade

diff --git a/tools/bkjs-redis b/tools/bkjs-redis
--- a/tools/bkjs-redis
+++ b/tools/bkjs-redis
@@ -78,6 +78,48 @@ case "$BKJS_CMD" in
     $KILLALL redis-sentinel
     ;;
 
+  init-monit-redis|init-redis-monit)
+    # There is no startup script because we rely on the monit to handle processes
+    [ "$(whoami)" != "root" ] && echo "Run as root please" && exit 1
+    echo 1 > /proc/sys/vm/overcommit_memory
+    echo never > /sys/kernel/mm/transparent_hugepage/enabled
+    if [ "$(grep -s 'overcommit_memory' /etc/sysctl.conf)" = "" ]; then
+       echo 'vm.overcommit_memory=1' >> /etc/sysctl.conf
+    fi
+    if [ "$(grep -s 'transparent_hugepage' /etc/rc.local)" = "" ]; then
+       echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' >> /etc/rc.local
+    fi
+    find_user
+    find_bkjsbin
+    $ECHO "$BKJS_HOME/log/redis.log {\n  weekly\n  rotate 10\n  copytruncate\n  delaycompress\n  compress\n  notifempty\n  missingok\n}" > /etc/logrotate.d/redis
+    $ECHO "check process redis-server with pidfile \"$BKJS_HOME/var/redis.pid\" start program = \"$BKJS_BIN run-redis $(get_all_args)\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$BKJS_BIN stop-redis\" if failed host 127.0.0.1 port 6379 for 2 cycles then restart" > /etc/monit.d/redis.conf
+    monit reload
+    ;;
+
+  init-monit-sentinel|init-sentinel-monit)
+    find_user
+    find_bkjsbin
+    host=$(get_arg -host 127.0.0.1)
+    port=$(get_arg -port 6379)
+    quorum=$(get_arg -quorum 2)
+    name=$(get_arg -name redis)
+    dtimeout=$(get_arg -down-timeout 10000)
+    ftimeout=$(get_arg -failover-timeout 180000)
+    conf=$BKJS_HOME/etc/sentinel.conf
+    $ECHO "daemonize yes" > $conf
+    $ECHO "syslog-enabled yes" >> $conf
+    $ECHO "sentinel monitor $name $host $port $quorum" >> $conf
+    $ECHO "sentinel down-after-milliseconds $name $dtimeout" >> $conf
+    $ECHO "sentinel failover-timeout $name $ftimeout" >> $conf
+    $ECHO "sentinel parallel-syncs $name 1" >> $conf
+    $ECHO "dir $BKJS_HOME/var/" >> $conf
+    $ECHO "pidfile $BKJS_HOME/var/sentinel.pid" >> $conf
+    chown $BKJS_USER $conf
+
+    $ECHO "check process redis-sentinel with pidfile \"$BKJS_HOME/var/sentinel.pid\" start program = \"$BKJS_BIN run-sentinel $(get_all_args)\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$BKJS_BIN stop-sentinel\"" > /etc/monit.d/sentinel.conf
+    monit reload
+    ;;
+
   help)
     echo ""
     echo "Redis commands:"
@@ -88,6 +130,8 @@ case "$BKJS_CMD" in
     echo "  stop-redis - stop local Redis server"
     echo "  run-sentinel - run local Redis Sentinel server, uses config file $REDIS_PREFIX/sentinel.conf"
     echo "  stop-sentinel - stop local Redis Sentinel server"
+    echo "  init-sentinel-monit [-host HOST] [-port PORT] - setup Redis Sentinel server to be run on start and to be monitored (Linux only)"
+    echo "  init-redis-monit [-memsize PERCENT] [-memmax SIZE] - setup Redis server to be run on start and to be monitored (Linux only)"
     echo ""
     ;;
 
