support reindex for alpine pkg index

diff --git a/tools/bkjs-alpine b/tools/bkjs-alpine
--- a/tools/bkjs-alpine
+++ b/tools/bkjs-alpine
@@ -4,7 +4,7 @@ case "$BKJS_CMD" in
 
   help|alpine-help)
     echo
-    echo "  alpine-abuild -file APKBUILD [-src .] [-repo REPO] [-image abuild] [-pkgver VER|PATH] [-pkgname N] [-sync S3] [-checksum] [-force] [-noexit] [-i] [-arch A] [-docker args] - build a package with alpine docker. Place the .apk into -repo folder and -sync to S3 if provided"
+    echo "  alpine-abuild -file APKBUILD [-checksum] [-reindex] [-src .] [-repo REPO] [-image abuild] [-pkgver VER|PATH] [-pkgname N] [-sync S3] [-force] [-noexit] [-i] [-arch A] [-docker args] - build a package with alpine docker. Place the .apk into -repo folder and -sync to S3 if provided"
     echo "  alpine-run-abuild -name N [-pkgname PKG] [-repo /repo] [-src /src] [-tmp /tmp] - call abuild for given APKBUILD.N file, place in -repo dir and run inside -tmp dir"
     echo "  alpine-prepare-abuild - build Docker image abuild for faster builds"
     echo
@@ -12,7 +12,11 @@ case "$BKJS_CMD" in
 
   alpine-abuild)
     file=$(get_arg -file)
-    [ -z "$file" -o ! -f "$file" ] && echo "-file is required and must exist" && exit 1
+    if [ -z "$file" -o ! -f "$file" ]; then
+        [ -z "$(get_flag -reindex)" ] && echo "-file is required and must exist" && exit 1
+        # reindex does not need a real build file
+        file=/dev/null
+    fi
 
     repo=$(get_arg -repo ${BKJS_APKDIR:-$HOME/alpine})
     mkdir -p $repo
@@ -64,7 +68,7 @@ case "$BKJS_CMD" in
         for s in $sync; do
             case $s in
             s3:*)
-              aws s3 sync $repo/ $s
+              aws s3 sync $repo/ $s --delete
               ;;
             esac
         done
@@ -88,10 +92,17 @@ case "$BKJS_CMD" in
 
     apk -U upgrade -a
 
+    cd $tmp
+
+    # Update index using fake build file and exit
+    if [ -n "$(get_flag -reindex)" ]; then
+        echo -e "pkgname=fake\npkgver=0.0.0\npkgrel=0\npkgdesc=fake\narch=noarch\n" > APKBUILD
+        abuild -P $repo -F -f index
+        exit
+    fi
+
     cp $file $tmp/APKBUILD
     [ "$?" != "0" ] && echo "invalid $file" && exit 1
-
-    cd $tmp
 
     # Update checksum and exit
     if [ -n "$(get_flag -checksum)" ]; then
@@ -117,7 +128,10 @@ case "$BKJS_CMD" in
         fi
     fi
 
-    abuild -P $repo -rFkK
+    # Inside docker no point to cleanup if container is destroyed anyway
+    [ -f /.dockerenv ] && keep="-kK"
+
+    abuild -P $repo -rF $keep
     rc=$?
 
     [ -n "$(get_flag -noexit)" ] && echo "Starting shell.." && /bin/sh -i
